### ISSUE TITLE
AttributeError after upgrading Node.js and sc.recipe.staticresources

### ISSUE THREAD

**Issue by hvelarde** [simplesconsultoria/sc.recipe.staticresources#34]
It's documented that after upgrading sc.recipe.staticresources to 1.0b1 you need to manually remove `parts/buildout-node` and `parts/node` directories. The problem is that after that buildout fails and the known workaround is just to run it again.

This seems to me like a bug in `gp.recipe.node`; I'm opening this issue here as a reminder to check upstream later:

```console
$ bin/buildout
...
Updating node.
While:
  Updating node.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/hvelarde/.buildout/eggs/zc.buildout-2.9.6-py2.7.egg/zc/buildout/buildout.py", line 2123, in main
    getattr(buildout, command)(args)
  File "/home/hvelarde/.buildout/eggs/zc.buildout-2.9.6-py2.7.egg/zc/buildout/buildout.py", line 766, in install
    installed_files = self[part]._call(update)
  File "/home/hvelarde/.buildout/eggs/zc.buildout-2.9.6-py2.7.egg/zc/buildout/buildout.py", line 1553, in _call
    return f()
  File "/home/hvelarde/.buildout/eggs/gp.recipe.node-6.2.2.1-py2.7.egg/gp/recipe/node/__init__.py", line 246, in update
    return self.install_scripts()
  File "/home/hvelarde/.buildout/eggs/gp.recipe.node-6.2.2.1-py2.7.egg/gp/recipe/node/__init__.py", line 173, in install_scripts
    node_bin = os.path.dirname(node_binary)
  File "/home/hvelarde/collective/buildout.python/python-2.7/lib/python2.7/posixpath.py", line 122, in dirname
    i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'
```
